dataset_path: AI4Math/MathVista
dataset_kwargs:
  token: True
task: "mathvista_testmini_cot"
test_split: testmini
tag: visual_reasoning_collection
output_type: generate_until
doc_to_visual: !function utils.mathvista_doc_to_visual
doc_to_text: !function utils.mathvista_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 128
  temperature: 0.0
  do_sample: false
  explore_nums: 5
  min_bs: 5
  keep_cot: True
  exp_temp: 0.5
process_results: !function utils.mathvista_process_results
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mathvista_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    shot_type: "step-by-step" # can be "reason-first", "solution", "step-by-step"
    shot: 0
    use_caption: False
    use_ocr: False
  phi3v:
    shot_type: "solution"