task: "mmmu_pro_vision_cot"
dataset_path: MMMU/MMMU_Pro
dataset_name: vision
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mmmu_pro_doc_to_visual
doc_to_text: "Write out the multiple-choice question in the image and then solve it. The last line of your response should be of the following format: 'Answer: $LETTER' (without quotes) where LETTER is one of options. Think step by step before answering."
doc_to_target: "{{answer}}"
# The return value of process_results will be used by metrics
process_results: !function utils.mmmu_pro_process_results

metric_list:
  - metric: mmmu_acc
    aggregation: !function utils.mmmu_pro_aggregate_results
    higher_is_better: true

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0.0
  do_sample: false
  explore_nums: 5
  min_bs: 5
  keep_cot: false
  exp_temp: 0.5

include: _default_template_yaml