dataset_path: MathLLMs/MathVision
dataset_kwargs:
  token: True
task: "mathvision_reason_test"
test_split: test
tag: visual_reasoning_collection
output_type: generate_until
doc_to_visual: !function utils.mathvision_doc_to_visual
doc_to_text: !function utils.mathvision_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 128
  temperature: 0.5
  do_sample: True
  explore_nums: 5
  min_bs: 5
  keep_cot: False
  exp_temp: 0.5
  until:
    - "</s>"
    - "Q:"
    - "<|im_end|>"
process_results: !function utils.mathvision_gpt_eval_process_results
metric_list:
  - metric: mathvision_gpt_eval_score
    aggregation: !function utils.mathvision_aggregate_results_eval
    higher_is_better: true