dataset_path: CaraJ/MathVerse-lmmseval
dataset_name: testmini_version_split
dataset_kwargs:
  token: False
task: "mathverse_testmini_vision_only"
test_split: vision_only
output_type: generate_until
doc_to_visual: !function utils.mathverse_doc_to_visual
doc_to_text: !function utils.mathverse_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  until:
    - "ASSISTANT:"
  max_new_tokens: 128
  temperature: 0.0
  do_sample: false
  explore_nums: 5
  min_bs: 5
  keep_cot: false
  exp_temp: 0.5
process_results: !function utils.mathverse_process_results
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mathverse_aggregate_results_eval
    higher_is_better: true
  - metric: submission
    aggregation: !function utils.mathverse_aggregate_results_submission
    higher_is_better: true
  
lmms_eval_specific_kwargs:
  default:
    shot_type: "format-prompt" # can also be "custom-prompt"
    query_type: "query_wo" # now only support query_wo
model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original

metadata:
  version: 0.0
  gpt_eval_model_name: "gpt-4o-2024-11-20" # or gpt-4o-2024-11-20
  trunk_response: 30
  quick_match: false